In [1]:
import numpy as np

In [47]:
A = np.array([[1, 2, 3], [2, 7, 4]])
B = np.array([[1, -1], [0, 1]])
C = np.array([[5, -1], [9, 1], [6, 0]])
D = np.array([[3, -2, -1], [1, 2, 3]])
u = np.array([6, 2, -3, 5])
v = np.array([3, 5, -1, 4])
w = np.array([[1], [8], [0], [5]])

## Matrix Dimensions

In [36]:
print('A Dimensions:', A.shape)
print('B Dimensions:', B.shape)
print('C Dimensions:', C.shape)
print('D Dimensions:', D.shape)
print('u Dimensions:', u.shape)
print('w Dimensions:', w.shape)

A Dimensions: (2, 3)
B Dimensions: (2, 2)
C Dimensions: (3, 2)
D Dimensions: (2, 3)
u Dimensions: (4,)
w Dimensions: (4, 1)


## Vector Operations

In [37]:
u + v

array([ 9,  7, -4,  9])

In [38]:
u - v

array([ 3, -3, -2,  1])

In [39]:
6*u

array([ 36,  12, -18,  30])

In [6]:
np.dot(u, v)

51

In [7]:
np.linalg.norm(u)

8.602325267042627

## Matric Operations

In [41]:
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [42]:
A - np.transpose(C)

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [43]:
np.transpose(C) + (3 * D)

array([[14,  3,  3],
       [ 2,  7,  9]])

In [48]:
B.shape, A.shape

((2, 2), (2, 3))

In [49]:
np.dot(B, A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [51]:
B.shape, np.transpose(A).shape

((2, 2), (3, 2))

In [50]:
np.dot(B, np.transpose(A))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [52]:
np.linalg.matrix_power(B, 4)

array([[ 1, -4],
       [ 0,  1]])

## Extra Exploration

In [53]:
B * C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [57]:
np.dot(B, C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [54]:
C * B

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [58]:
np.dot(C, B)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

**Use dot product rather than arithmetic symbol when performing matrix operations**

In [59]:
A * np.transpose(A)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [60]:
np.dot(A, np.transpose(A))

array([[14, 28],
       [28, 69]])

In [61]:
D * np.transpose(D)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [62]:
np.dot(D, np.transpose(D))

array([[14, -4],
       [-4, 14]])

In [24]:
a.shape

(2, 3)

In [26]:
c.shape

(3, 2)

In [27]:
b.shape

(2, 2)

In [28]:
np.transpose(a).shape

(3, 2)

In [30]:
np.transpose(d).shape

(3, 2)

In [31]:
d.shape

(2, 3)

In [32]:
np.transpose(a).shape

(3, 2)